### ISSUE TITLE
serviceWithRabbit sometimes throw

### ISSUE THREAD

**Issue by yamalight** [Exynize/exynize-rest#36]
Stack trace:

```
error: [rest-api] unhandled rejection: TypeError: Cannot read property 'map' of undefined
  at step (serviceWithRabbit.js:5:1)
  at tryCatch (/opt/app/node_modules/babel-regenerator-runtime/runtime.js:61:40)
  at AutoDetachObserverPrototype.dispose (/opt/app/node_modules/rx/dist/rx.js:5907:14)
  at [object Object].SingleAssignmentDisposable.dispose (/opt/app/node_modules/rx/dist/rx.js:736:18)
  at [object Object].SingleAssignmentDisposable.dispose (/opt/app/node_modules/rx/dist/rx.js:736:18)
```

**Comment by yamalight** [comment]
seems like it was due to regression in deps. verify that it doesn't happen.

**Comment by yamalight** [comment]
seems to be fine, closing for now
